name: Build and Publish Wheels

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Choco help
      uses: crazy-max/ghaction-chocolatey@v3
      with:
        args: install python --version=3.10.0

    - name: Install dependencies
      run: |
        pip install setuptools wheel

    - name: Build and package C extensions
      run: |
        python setup.py sdist bdist_wheel

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheel-windows
        path: dist

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist
      - name: Create release
        id: release
        uses: ncipollo/release-action@v1
        with:
          tag: maze
          name: "maze"
          commit: main
          makeLatest: true
          allowUpdates: true
          removeArtifacts: true
          artifacts: dist/*.whl
      - name: Release URL
        run: |
          echo "Release URL: ${{ steps.release.outputs.html_url }}"
